### ISSUE TITLE
Provide an embeddable badge generator

### ISSUE THREAD

**Issue by matks** [PrestaShop/QANightlyResults#17]
Software projects on github love to put badges like this:
<img width="473" alt="Capture d’écran 2020-01-28 à 15 18 12" src="https://user-images.githubusercontent.com/3830050/73271731-6cfa2000-41e1-11ea-974a-866bf03b8d1a.png">

It would be awesome to have one for nightly results that we can put in PrestaShop core README

See https://shields.io/ for examples

**Comment by SimonGrn** [comment]
That's cute, I can provide an endpoint to get any data from the board. The question is, what exactly do you want to show ? Results from the last execution ? For any branch ?

**Comment by SimonGrn** [comment]
Done, through the endpoint `/data/badge`
